---
spring:
  application:
    name: cloud-native-spring
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  main:
    allow-bean-definition-overriding: true


info: # add this section
  build:
    artifact: cloud-native-spring
    name: cloud-native-spring
    description: Demo project for Spring Boot
    version: 0.0.1-SNAPSHOT

feign:
  httpclient:
    disableSslValidation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: cloud

feign:
   httpclient:
     disableSslValidation: false

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

